---
services:
  model:
    image: model
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7026:7026"
    volumes:
      - ./main.py:/main.py
    environment:
      - MODEL_PATH=main.py
      - MODEL_PORT=7026
